-- AlterTable
ALTER TABLE "quote_snapshots" ALTER COLUMN "pl" DROP NOT NULL,
ALTER COLUMN "pvp" DROP NOT NULL,
ALTER COLUMN "ev_ebitda" DROP NOT NULL,
ALTER COLUMN "roe" DROP NOT NULL,
ALTER COLUMN "roic" DROP NOT NULL,
ALTER COLUMN "net_margin" DROP NOT NULL,
ALTER COLUMN "gross_margin" DROP NOT NULL,
ALTER COLUMN "lpa" DROP NOT NULL,
ALTER COLUMN "vpa" DROP NOT NULL,
ALTER COLUMN "ebitda" DROP NOT NULL,
ALTER COLUMN "net_debt_ebitda" DROP NOT NULL;
